db:
  host: process.env.HOST || 'production-host',
  username: process.env.DATABASE_USERNAME || 'production-username',
  password: process.env.DATABASE_PASSOWRD || 'production-password',
  database: process.env.DATABASE_NAME || 'production-database',
  synchronize: true
